[gist]:https://gist.github.com/anonhostpi/97d4bb3e9535c92b8173fae704b76264#file-_topics-0005-api-0002-access-connectivity-md
[source]:https://github.com/anonhostpi/AUTOGPT.TRACKERS/blob/main/TOPICS/0005.API/0002.ACCESS/CONNECTIVITY.md
# API Disconnect/Connectivity Problems:
## Issues:
- [#3977][3977] - Errno 101 - Network is unreachable
- [#3728][3728] - Connection Aborted - Remote end closed connection without response
- [#3607][3607] - Proposal to handle 401+/500+ errors from the OpenAI Python module
- [#2937][2937] - Request Timed Out
- [#2553][2553] - HTTP Response Code 500 from OpenAI Python module
- [#2241][2241] - Connection Aborted - Remote end closed connection without response
- [#1010][1010] - Errno 101 - Network is unreachable

## Useful Links:
[Gist][gist] | [Alt][source]
- OpenAI Status: http://status.openai.com/

## Common Responses:
```md
Make sure to check http://status.openai.com/ and recommend checking 3rd parties like downdetector: https://downdetector.com/status/openai/
```

[2241]:https://github.com/Significant-Gravitas/Auto-GPT/issues/2241
[2553]:https://github.com/Significant-Gravitas/Auto-GPT/issues/2553
[2937]:https://github.com/Significant-Gravitas/Auto-GPT/issues/2937
[3607]:https://github.com/Significant-Gravitas/Auto-GPT/issues/3607
[3728]:https://github.com/Significant-Gravitas/Auto-GPT/issues/3728
[3977]:https://github.com/Significant-Gravitas/Auto-GPT/issues/3977